/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ba.senai.view;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class Tela extends javax.swing.JFrame {
    
    DefaultListModel<String> model;
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        
        model = new DefaultListModel<>();
        listaFruta.setModel(model);
        setSize(570, 505);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbm = new javax.swing.JRadioButton();
        rbt = new javax.swing.JRadioButton();
        ck = new javax.swing.JCheckBox();
        cbFruta = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFruta = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tfFruta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        buttonGroup1.add(rbm);
        rbm.setText("Manhã");
        getContentPane().add(rbm);
        rbm.setBounds(26, 19, 70, 28);

        buttonGroup1.add(rbt);
        rbt.setText("Tarde");
        getContentPane().add(rbt);
        rbt.setBounds(26, 49, 65, 28);

        ck.setText("Usar showInput");
        getContentPane().add(ck);
        ck.setBounds(399, 21, 140, 30);

        cbFruta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(cbFruta);
        cbFruta.setBounds(26, 83, 510, 26);

        listaFruta.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaFruta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(26, 115, 510, 147);

        jButton1.setText("Excluir Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 380, 160, 32);

        jButton2.setText("Consultar Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 420, 160, 32);

        jButton3.setText("Inserir ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 340, 160, 32);
        getContentPane().add(tfFruta);
        tfFruta.setBounds(26, 296, 510, 24);

        jLabel1.setText("Fruta: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 274, 35, 16);

        jButton7.setText("Ver Todos selecionados");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObterDados(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(349, 338, 190, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Inserir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir
        // TODO add your handling code here:
        if(ck.isSelected()){
            String fruta = JOptionPane.showInputDialog("Digite a fruta:");
            cbFruta.addItem(fruta);
            model.addElement(fruta);
        }else{
            cbFruta.addItem(tfFruta.getText());
            model.addElement(tfFruta.getText());
        }
        tfFruta.setText("");
        tfFruta.requestFocus();
    }//GEN-LAST:event_Inserir

    private void Excluir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "Deseja excluir o item?", "exemplo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(op==0){
            cbFruta.removeItemAt(cbFruta.getSelectedIndex());
            model.removeElementAt(listaFruta.getSelectedIndex());
        }
    }//GEN-LAST:event_Excluir

    private void Consultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Combo: "+cbFruta.getSelectedItem()+"   Lista: "+listaFruta.getSelectedValue());
    }//GEN-LAST:event_Consultar

    private void ObterDados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObterDados
        // TODO add your handling code here:
        if(rbm.isSelected()){
            JOptionPane.showMessageDialog(null, "Manha");
        }else{
            JOptionPane.showMessageDialog(null, "Tarde");
        }
    }//GEN-LAST:event_ObterDados

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbFruta;
    private javax.swing.JCheckBox ck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaFruta;
    private javax.swing.JRadioButton rbm;
    private javax.swing.JRadioButton rbt;
    private javax.swing.JTextField tfFruta;
    // End of variables declaration//GEN-END:variables
}
