+// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ConversorTest {
  
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "test//chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void conversor() throws InterruptedException {
    
    driver.get("http://localhost:8080/Conversor/");
    driver.manage().window().setSize(new Dimension(516, 745));
    driver.findElement(By.name("value")).click();
    driver.findElement(By.name("value")).sendKeys("100");
    driver.findElement(By.cssSelector(".container:nth-child(2)")).click();
    driver.findElement(By.name("calcular")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Resultado: 212.0"));
    Thread.sleep(5000);
    driver.navigate().back();
    driver.findElement(By.name("value")).click();
    driver.findElement(By.name("value")).clear();
    driver.findElement(By.name("value")).sendKeys("212");
    driver.findElement(By.cssSelector(".container:nth-child(3)")).click();
    driver.findElement(By.name("calcular")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Resultado: 100.0"));
    driver.findElement(By.cssSelector("html")).click();
    Thread.sleep(5000);
  }
}
